language: python
python:
  - "3.8"
before_install:
  - pip install --upgrade pip
  - pip install poetry black
install:
  - poetry install
jobs:
  include:
    - stage: lint
      script: make lint
      script: make black
    - stage: test
      script: make test